meh/rust-tun

- src/platform/linux/device.rs
- src/platform/macos/device.rs
- src/platform/posix/fd.rs
I noticed the lack of `AsRawFd` for the `Device` struct on MacOS, so I've implemented that and also `IntoRawFd`, as that's my _actual_ use case. If however you don't wish to have the device be capable of being irreversibly turned into a raw file descriptor, I'm OK with not making that change :slightly_smiling_face:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/meh/rust-tun/10)
> Add raw fd traits

- src/configuration.rs
- src/device.rs
With this simple change I am able to run my code as unprivileged user.
I can set ip address and bring up interface from shell script or systemd, and then run my application as a normal user instead of root.
> Don't try to enable interface unless requested.

- src/configuration.rs
- src/error.rs
- src/lib.rs
- src/platform/linux/device.rs
- src/platform/linux/sys.rs
- src/platform/macos/device.rs
This commit adds support for L2 tun devices.
L2 tun devices are supported only on Linux, so trying to create one on
OSX will return an UnsupportedLayer error.
> feat: add L2 devices support

- src/async/device.rs
- src/async/mod.rs
- src/configuration.rs
- src/device.rs
- src/error.rs
- src/platform/linux/device.rs
- src/platform/linux/mod.rs
- src/platform/linux/sys.rs
- src/platform/macos/device.rs
- src/platform/macos/mod.rs
- src/platform/mod.rs
This commit adds support for multiqueue interfaces.
Multiqueue devices are supported only on Linux, so trying to create a
device with more than one queue on OSX will return an
InvalidQueuesNumber error.
> feat: add multiqueue support

- src/async/codec.rs
This pr should fix #17, but I don't exactly know why malformed packets are coming from macOS's tun interface.
> fix: ignore malformed packets while decoding

- src/async/codec.rs
- src/async/device.rs
The root cause of #17 is the codec fails to reserve enough space for the every packet and resulting truncated packets.
> fix: reserve enough space for packet decoding

- Cargo.toml
This adds support for Apple Silicon. Support for it in ioctl-sys was introduced in this PR: https://github.com/jmesmon/ioctl/pull/7
> Bump ioctl-sys to 0.6

- src/platform/posix/sockaddr.rs
The fix only consider mips/mips64 as I don't have access
to other platforms that I can test on.
> fix: properly handle endianness for big-endian targets

- src/platform/android/device.rs
- src/platform/android/mod.rs
- src/platform/mod.rs
- src/platform/posix/sockaddr.rs
I added a module `android` by simply copying the code and renaming the structs from the `ios` module, and it works well on my Android 10 device.
`VpnService.builder` in Android works like iOS (#21). The tunnel device's file descriptor can be created in Java code and then be passed to the native Rust code.
> feat: add Android support

- Cargo.toml
- src/async/device.rs
- src/platform/android/device.rs
- src/platform/ios/device.rs
- src/platform/linux/device.rs
- src/platform/macos/device.rs
- src/platform/posix/fd.rs
- src/platform/posix/sockaddr.rs
Specifically this commit:
* Upgrades tokio to v1.x
* Updates all dependencies to their latest stable version
* Implements the async feature instead by tokio's AsyncFd
* Implements AsRawFd for types that need the async interface
* Removes all mio-related stuffs
> Upgrade tokio to v1.x

- src/platform/android/device.rs
- src/platform/ios/device.rs
- src/platform/linux/device.rs
- src/platform/macos/device.rs
- src/platform/posix/fd.rs
Non-blocking mode shouldn't be bound with `async`.
> feat: Allow setting non-blocking mode without enabling async

- src/platform/posix/fd.rs
Attempting to use vectored read/write on linux was resulting in ENOTSOCK.
Fixes #43.
> Use readv/writev instead of recvmsg/sendmsg

- src/async/codec.rs
This comment add a function TunPacket::into_bytes() to struct TunPacket, which allows users to consume `TunPacket` and return the inner `Bytes` instences.
Thus we can avoid copy in the following code:
```rust
let bytes = Bytes::from(packet.get_bytes().to_owned())
```
> feat: add TunPacket::into_bytes()

- src/platform/macos/device.rs
Currently, you can't set the `netmask` in macos system. It will always be `netmask 0xff000000`, no matter what kind of netmask is given to the program.
Seems command `siocsifnetmask` doesn't work as expected. The fix tries to make another system call `siocaifaddr`, which was defined but not used.
Tophatting:
> Fix the issue of macos netmask setting

- src/platform/linux/device.rs
before https://github.com/meh/rust-tun/pull/41 had been merged by [0e4ef622](https://github.com/0e4ef622), but removed somehow.
I just want to add it again.
> Add split in platform::linux::Device again

- src/platform/macos/device.rs
Current implementation, if you set `utun10` in `name`, then the actual `utun` device name is `utun9`. If the `name` is set to `utun0`, then it actually tells the kernel to dynamically allocate a free id for it.
ref https://github.com/shadowsocks/shadowsocks-rust/issues/1176
> fix(macOS): sc_unit should be the number in name + 1

- Cargo.toml
There is an incompatibility of the `Framed` struct between versions 0.6 and 0.7 that prevents using them simultaneously.
> fix(deps): update tokio-utils to 0.7

- .github/workflows/rust.yml
- Cargo.toml
- README.md
- examples/ping-tun.rs
- examples/read-async.rs
- examples/read.rs
- src/async/codec.rs
- src/async/device.rs
- src/async/win/device.rs
- src/error.rs
- src/platform/linux/device.rs
- src/platform/linux/mod.rs
- src/platform/macos/device.rs
- src/platform/macos/sys.rs
- src/platform/windows/device.rs
- src/platform/windows/mod.rs
due to libc crate updated, ifreq struct added
> clean code

- src/configuration.rs
- src/platform/macos/device.rs
- src/platform/macos/mod.rs
We would like the option to disable the invocation of `route` on macOS, since we want to set up all routes ourselves. Improvement suggestions are welcome!
> feat: add option to disable route setup on macOS

- .cargo/config.toml
Added all 4 android architectures as target.
| Android ABI      | Rust Target                  | Notes                  |
|------------------|------------------------------|------------------------|
| `arm64-v8a`      | `aarch64-linux-android`      | 64-bit ARM (modern)    |
| `armeabi-v7a`    | `armv7-linux-androideabi`    | 32-bit ARM (legacy)    |
| `x86`            | `i686-linux-android`         | 32-bit Intel (rare)    |
| `x86_64`         | `x86_64-linux-android`       | 64-bit Intel (emulator)|
> Add all android cpu architecture

- Cargo.toml
We're having some issues with the verification being very slow, possibly because our app blocks internet traffic. (This is only a guess.)
In our case, we do not want/need the check, as we can already trust the that the correct DLL is being loaded, and we point to it using its absolute path. So we would like to to disable it.
I'm not sure if this solution is ideal, since it's still pretty easy to accidentally enable the feature with `tun` as a transitive dependency. Would you be open to this being a configurable option instead?
> Make it possible to disable wintun.dll verification

- Cargo.toml
- src/platform/windows/device.rs
This should be a bit nicer and faster than relying on netsh.
> Replace netsh for setting interface metrics
